### ISSUE TITLE
false positive: aws_ebs_volume is found missing

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#562]
**Description**

driftctl 0.9.0 reports a missing `aws_ebs_volume`: 

```shell 
Scanned states (1)      
Scanned resources (51)      
Found missing resources:
  aws_ebs_volume:
    - vol-000e2dffd7f09fdc0
[...]
``` 

The said volume is available tho: 

```
$ aws ec2 describe-volumes --volume-ids vol-000e2dffd7f09fdc0

{
    "Volumes": [
        {
            "Attachments": [
                {
                    "AttachTime": "2021-05-05T06:26:01+00:00",
                    "Device": "/dev/xvdd",
                    "InstanceId": "i-0a85fc94dad0eee9a",
                    "State": "attached",
                    "VolumeId": "vol-000e2dffd7f09fdc0",
                    "DeleteOnTermination": false
                }
            ],
            "AvailabilityZone": "eu-west-3a",
            "CreateTime": "2021-05-05T06:25:39.455000+00:00",
            "Encrypted": true,
            "KmsKeyId": "arn:aws:kms:eu-west-3:943295019655:key/a53ba348-5a9a-4f86-8cd3-86698e80ac39",
            "Size": 125,
            "SnapshotId": "",
            "State": "in-use",
            "VolumeId": "vol-000e2dffd7f09fdc0",
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "aws-www-1-data"
                }
            ],
            "VolumeType": "st1",
            "MultiAttachEnabled": false
        }
    ]
}
```

Table version for readability if needed: 

```
---------------------------------------------------------------------------------------------------------
|                                            DescribeVolumes                                            |
+-------------------------------------------------------------------------------------------------------+
||                                               Volumes                                               ||
|+--------------------+--------------------------------------------------------------------------------+|
||  AvailabilityZone  |  eu-west-3a                                                                    ||
||  CreateTime        |  2021-05-05T06:25:39.455000+00:00                                              ||
||  Encrypted         |  True                                                                          ||
||  KmsKeyId          |  arn:aws:kms:eu-west-3:943295019655:key/a53ba348-5a9a-4f86-8cd3-86698e80ac39   ||
||  MultiAttachEnabled|  False                                                                         ||
||  Size              |  125                                                                           ||
||  SnapshotId        |                                                                                ||
||  State             |  in-use                                                                        ||
||  VolumeId          |  vol-000e2dffd7f09fdc0                                                         ||
||  VolumeType        |  st1                                                                           ||
|+--------------------+--------------------------------------------------------------------------------+|
|||                                            Attachments                                            |||
||+-------------------------------------------+-------------------------------------------------------+||
|||  AttachTime                               |  2021-05-05T06:26:01+00:00                            |||
|||  DeleteOnTermination                      |  False                                                |||
|||  Device                                   |  /dev/xvdd                                            |||
|||  InstanceId                               |  i-0a85fc94dad0eee9a                                  |||
|||  State                                    |  attached                                             |||
|||  VolumeId                                 |  vol-000e2dffd7f09fdc0                                |||
||+-------------------------------------------+-------------------------------------------------------+||
|||                                               Tags                                                |||
||+--------------------------------+------------------------------------------------------------------+||
|||  Key                           |  Name                                                            |||
|||  Value                         |  aws-www-1-data                                                  |||
||+--------------------------------+------------------------------------------------------------------+||

```

**Environment**
 - OS: fedora 34
 - driftctl version: 0.9.0 (previous versions affected too)

**How to reproduce**

The following HCL is used: 

```hcl
resource "aws_ebs_volume" "aws-www-1-data" {
  availability_zone = "eu-west-3a"
  size              = 125
  type              = "st1" # Throughput Optimized HDD
  encrypted         = true

  tags = {
    Name = "aws-www-1-data"
  }
}
```
Here's the representation in the state: 

```
$ terraform state show aws_ebs_volume.aws-www-1-data
# aws_ebs_volume.aws-www-1-data:
resource "aws_ebs_volume" "aws-www-1-data" {
    arn                  = "arn:aws:ec2:eu-west-3:943295019655:volume/vol-000e2dffd7f09fdc0"
    availability_zone    = "eu-west-3a"
    encrypted            = true
    id                   = "vol-000e2dffd7f09fdc0"
    iops                 = 0
    kms_key_id           = "arn:aws:kms:eu-west-3:943295019655:key/a53ba348-5a9a-4f86-8cd3-86698e80ac39"
    multi_attach_enabled = false
    size                 = 125
    tags                 = {
        "Name" = "aws-www-1-data"
    }
    throughput           = 0
    type                 = "st1"
}

```

Here are the different representations in the state itself.

First the `aws_ebs_volume`: 

```json

    {
      "mode": "managed",
      "type": "aws_ebs_volume",
      "name": "aws-www-1-data",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:ec2:eu-west-3:943295019655:volume/vol-000e2dffd7f09fdc0",
            "availability_zone": "eu-west-3a",
            "encrypted": true,
            "id": "vol-000e2dffd7f09fdc0",
            "iops": 0,
            "kms_key_id": "arn:aws:kms:eu-west-3:943295019655:key/a53ba348-5a9a-4f86-8cd3-86698e80ac39",
            "multi_attach_enabled": false,
            "outpost_arn": "",
            "size": 125,
            "snapshot_id": "",
            "tags": {
              "Name": "aws-www-1-data"
            },
            "throughput": 0,
            "type": "st1"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    },

```

Then the `instances` section 

```json
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "ami": "ami-039233e7845c61711",
            "arn": "arn:aws:ec2:eu-west-3:943295019655:instance/i-0a85fc94dad0eee9a",
            "associate_public_ip_address": true,
            "availability_zone": "eu-west-3a",
            "cpu_core_count": 2,
            "cpu_threads_per_core": 2,
            "credit_specification": [
              {
                "cpu_credits": "unlimited"
              }
            ],
            "disable_api_termination": false,
            "ebs_block_device": [
              {
                "delete_on_termination": false,
                "device_name": "/dev/xvdd",
                "encrypted": true,
                "iops": 0,
                "kms_key_id": "arn:aws:kms:eu-west-3:943295019655:key/a53ba348-5a9a-4f86-8cd3-86698e80ac39",
                "snapshot_id": "",
                "tags": {
                  "Name": "aws-www-1-data"
                },
                "throughput": 0,
                "volume_id": "vol-000e2dffd7f09fdc0",
                "volume_size": 125,
                "volume_type": "st1"
              }
            ],
```

Finally the `aws_volume_attachment` part: 

```json
      "mode": "managed",
      "type": "aws_volume_attachment",
      "name": "aws-www-1-data",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "device_name": "/dev/xvdd",
            "force_detach": null,
            "id": "vai-2313885580",
            "instance_id": "i-0a85fc94dad0eee9a",
            "skip_destroy": null,
            "volume_id": "vol-000e2dffd7f09fdc0"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "aws_internet_gateway.gw",
            "aws_key_pair.admin",
            "aws_security_group.ssh",
            "aws_security_group.www",
            "aws_subnet.production-subnet-1",
            "aws_vpc.production",
            "aws_ebs_volume.aws-www-1-data",
            "aws_instance.aws-www-1"
          ]
        }
      ]
    },
```

**Possible Solution**

**Additional context**

Terraform 0.15.1 & AWS provider 3.37.0

**Comment by sjourdan** [comment]
can't reproduce ... because this infrastructure moved to TF 1.0.0 and provider 3.46.0 

we should try to qualify this one with original requirements (don't have the time right now)

**Comment by sjourdan** [comment]
issue confirmed with 0.10

```
Found missing resources:
  aws_ebs_volume:
    - vol-000e2dffd7f09fdc0
```

issue fixed with 0.11 

```
Found 26 resource(s)   
 - 100% coverage
Congrats! Your infrastructure is fully in sync.
Scan duration: 3s
```

LGTM!

**Comment by n2N8Z** [comment]
This issue still exists in driftctl-0.38.2 when a volume is listed in state for an instance as both the root volume and an ebs volume.
I was able to work around the issue by removing the instance from state (state rm), and then re-importing it. After re-import the volume is only listed as a root volume on the instance. So there may be some TF state cruft going on here that's causing problems for driftctl.
